version: "3.9"

services:

  minecraft:
    build:
      context: ./
      dockerfile: docker/minecraft/Dockerfile
    container_name: minecraft
    image: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: True
      INIT_MEMORY: 2G
      MAX_MEMORY: 32G
    volumes:
    - ./data:/data

networks:
  default:
    name: minecraft_network
